nelmio_api_doc:
    documentation:
        info:
            title: Api Core V1 RaspinuOffice
            description: Documentation for the correct use of the api
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
